[package]
name = "blazinterner"
description = "Efficient and concurrent interning of generic data"
version = "0.5.1"
authors = ["Guillaume Endignoux <ggendx@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/gendx/blazinterner"
categories = ["caching", "memory-management", "concurrency"]
keywords = ["arena", "interning", "interner"]
exclude = [".github/*"]
edition = "2024"
rust-version = "1.91.0"

[package.metadata.docs.rs]
features = ["debug", "delta", "get-size2", "raw", "retain", "serde", "std", "sync"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[features]
default = ["std", "sync"]
debug = ["get-size2"]
delta = []
get-size2 = ["dep:get-size2", "appendvec?/get-size2", "dashtable?/get-size2"]
raw = []
retain = ["dep:bit-set"]
serde = ["dep:serde"]
std = []
sync = ["dep:appendvec", "dep:dashtable"]

[dependencies]
appendvec = { optional = true, version = "0.1.6" }
bit-set = { optional = true, version = "0.11.1", default-features = false }
dashtable = { optional = true, version = "0.2.1" }
either = { version = "1.17.0", default-features = false }
get-size2 = { optional = true, version = "0.11.0", default-features = false, features = ["alloc", "derive", "hashbrown"] }
hashbrown = "0.17.1"
serde = { optional = true, version = "1.0.229", default-features = false, features = ["derive"] }
serde_cow = "0.1.2"

[dev-dependencies]
postcard = { version = "1.1.3", features = ["use-std"] }
serde_json = "1.0.151"
