on: [push, pull_request]
name: Code coverage
jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C debug_assertions"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage (all features except sync)
        run: cargo llvm-cov --verbose --release --no-default-features --features=debug,delta,get-size2,raw,retain,serde --workspace --lcov --output-path lcov-no-sync.info
      - name: Generate code coverage (all features)
        run: cargo llvm-cov --verbose --release --all-features --workspace --lcov --output-path lcov-all.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov-no-sync.info,lcov-all.info
          verbose: true
          fail_ci_if_error: true
